---
#This playbook install and configure my basic laptop packages
- hosts: localhost
  sudo: true
  tasks:
  - name: Install repositories
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
  - name: Install RPMfusion repos
    shell: "su -c 'dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'"
  - name: Install Spotify repository
    shell: "dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo"
  - name: Install package groups(Development, virtualization, Security, System, Administration, Cloud Management and Container Management)
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - "@Development Tools"
      - "@Virtualization"
      - "@Security Lab"
      - "@System Tools"
      - "@Administration Tools"
      - "@Cloud Management Tools"
      - "@Container Management"
      - eclipse
      - vagrant
      - vagrant-libvirt
      - python-openstackclient
      - python-glanceclient
      - python-neutronclient
      - python-heatclient
  - name: Install other tools
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - spotify-client
      - firefox
      - flash-plugin
      - nspluginwrapper
      - alsa-plugins-pulseaudio
      - libcurl
      - vlc
      - gstreamer-ffmpeg
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free
      - gstreamer-plugins-bad-free-extras
      - gstreamer-plugins-bad-nonfree
      - gstreamer-plugins-base
      - gstreamer-plugins-good
      - gstreamer-plugins-ugly 
      - faad2
      - faac
      - libdca
      - wget
      - compat-libstdc++-33
      - compat-libstdc++-296
      - xine-lib-extras-freeworld
      - dia
      - gparted
      - nmap
      - clamav
      - clamtk
      - nixnote2
      - libreoffice
      - xchat
      - git
      - git-review
      - skype
  - name: Install customization tools
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - cairo-dock
      - gnome-tweak-tool
